// <auto-generated />
using System;
using HeadendHQ.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HeadendHQ.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260911180034_SelectableLogos")]
    partial class SelectableLogos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("HeadendHQ.Core.Catalog.Broadcasters.Broadcaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("Aliases")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AndroidPackage")
                        .HasColumnType("TEXT");

                    b.Property<string>("CallLetters")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DetailFetchedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalId")
                        .HasColumnType("TEXT");

                    b.Property<string>("IptvGuideNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAffiliate")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSubscribed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MapsToBroadcasterId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ShortName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceKey")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.HasIndex("SourceKey", "ExternalId");

                    b.ToTable("Broadcasters", (string)null);
                });

            modelBuilder.Entity("HeadendHQ.Core.Catalog.Leagues.League", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Abbreviation")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsFollowed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ShortName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceKey")
                        .HasColumnType("TEXT");

                    b.Property<int>("SportId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SupportsTeams")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("TeamsRefreshedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.HasIndex("SportId");

                    b.HasIndex("SourceKey", "ExternalId");

                    b.ToTable("Leagues", (string)null);
                });

            modelBuilder.Entity("HeadendHQ.Core.Catalog.Sports.Sport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExternalId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceKey")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.HasIndex("SourceKey", "ExternalId");

                    b.ToTable("Sports", (string)null);
                });

            modelBuilder.Entity("HeadendHQ.Core.Catalog.Teams.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Abbreviation")
                        .HasColumnType("TEXT");

                    b.Property<string>("AlternateColorHex")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsFollowed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LeagueId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Location")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LogosVerifiedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nickname")
                        .HasColumnType("TEXT");

                    b.Property<string>("PrimaryColorHex")
                        .HasColumnType("TEXT");

                    b.Property<string>("ShortDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceKey")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LeagueId", "DisplayName")
                        .IsUnique();

                    b.HasIndex("SourceKey", "ExternalId");

                    b.ToTable("Teams", (string)null);
                });

            modelBuilder.Entity("HeadendHQ.Core.Events.SportingEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int?>("AwayTeamId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AwayTeamName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("BroadcasterId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DetailsFetchedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("HomeTeamId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HomeTeamName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("LeagueId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SeasonType")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SeasonYear")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SeriesSummary")
                        .HasColumnType("TEXT");

                    b.Property<string>("SeriesType")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("TitleId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Variant")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VenueName")
                        .HasColumnType("TEXT");

                    b.Property<string>("WatchUrl")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StartUtc");

                    b.HasIndex("TitleId");

                    b.HasIndex("SourceKey", "ExternalId")
                        .IsUnique();

                    b.ToTable("SportingEvents", (string)null);
                });

            modelBuilder.Entity("HeadendHQ.Core.Iptv.IptvChannel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CallSign")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("GuideNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IconUrl")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("LastSeenUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CallSign");

                    b.HasIndex("GuideNumber")
                        .IsUnique();

                    b.ToTable("IptvChannels", (string)null);
                });

            modelBuilder.Entity("HeadendHQ.Core.Iptv.IptvGuideCache", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("IptvGuideCache", (string)null);
                });

            modelBuilder.Entity("HeadendHQ.Core.Iptv.IptvProgramme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChannelId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("GuideNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StopUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("SubTitle")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GuideNumber", "StartUtc");

                    b.ToTable("IptvProgrammes", (string)null);
                });

            modelBuilder.Entity("HeadendHQ.Core.Media.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Bytes")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ETag")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("FetchedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LastModifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("LeagueId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Origin")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Purpose")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceUrl")
                        .HasColumnType("TEXT");

                    b.Property<int>("Width")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Sha256")
                        .IsUnique();

                    b.HasIndex("Purpose", "LeagueId");

                    b.HasIndex("SourceUrl", "Purpose")
                        .IsUnique()
                        .HasFilter("\"SourceUrl\" IS NOT NULL");

                    b.ToTable("Images", (string)null);
                });

            modelBuilder.Entity("HeadendHQ.Core.Settings.GlobalSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("PublicBaseUrl")
                        .HasColumnType("TEXT");

                    b.Property<int>("TitleRetentionDays")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("GlobalSettings", (string)null);
                });

            modelBuilder.Entity("HeadendHQ.Core.Settings.ScheduleScrapingSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxAthletesPerTeam")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(12);

                    b.Property<int>("ScrapeWindowDays")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ScheduleScrapingSettings", (string)null);
                });

            modelBuilder.Entity("HeadendHQ.Core.Titles.Title", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AdbCommand")
                        .HasColumnType("TEXT");

                    b.Property<bool>("ArtworkCreated")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BackgroundImageId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ClearLogoImageId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentRating")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventUrl")
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("Genres")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsLive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsVideoCreated")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LaunchSlug")
                        .HasColumnType("TEXT");

                    b.Property<string>("LiveJobId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Plot")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PosterImageId")
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("Sets")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SourceId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Studio")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tagline")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ThumbnailImageId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UniqueId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("VodLauncherPath")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SourceId");

                    b.HasIndex("StartUtc");

                    b.ToTable("Titles", (string)null);
                });

            modelBuilder.Entity("HeadendHQ.HdHomerun.HdHomerunSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DeviceUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("HdHomerunSettings", (string)null);
                });

            modelBuilder.Entity("HeadendHQ.VodLauncher.VodLauncherSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("LibraryPaths")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("VodLauncherSettings", (string)null);
                });

            modelBuilder.Entity("HeadendHQ.Core.Catalog.Broadcasters.Broadcaster", b =>
                {
                    b.OwnsMany("HeadendHQ.Core.Catalog.Broadcasters.BroadcasterLogo", "Logos", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER");

                            b1.Property<int>("BroadcasterId")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("ImageId")
                                .HasColumnType("INTEGER");

                            b1.Property<bool>("IsSelected")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Label")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Origin")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Variant")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("Id");

                            b1.HasIndex("BroadcasterId", "Variant", "Label")
                                .IsUnique();

                            b1.ToTable("BroadcasterLogos", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("BroadcasterId");
                        });

                    b.Navigation("Logos");
                });

            modelBuilder.Entity("HeadendHQ.Core.Catalog.Leagues.League", b =>
                {
                    b.OwnsMany("HeadendHQ.Core.Catalog.Leagues.LeagueLogo", "Logos", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER");

                            b1.Property<int>("ImageId")
                                .HasColumnType("INTEGER");

                            b1.Property<bool>("IsSelected")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Label")
                                .HasColumnType("TEXT");

                            b1.Property<int>("LeagueId")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Origin")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Variant")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("Id");

                            b1.HasIndex("LeagueId", "Variant", "Label")
                                .IsUnique();

                            b1.ToTable("LeagueLogos", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("LeagueId");
                        });

                    b.OwnsMany("HeadendHQ.Core.Catalog.Leagues.LeagueWordmark", "Wordmarks", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER");

                            b1.Property<int>("ImageId")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("LeagueId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Variant")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("Id");

                            b1.HasIndex("LeagueId", "Variant")
                                .IsUnique();

                            b1.ToTable("LeagueWordmarks", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("LeagueId");
                        });

                    b.Navigation("Logos");

                    b.Navigation("Wordmarks");
                });

            modelBuilder.Entity("HeadendHQ.Core.Catalog.Teams.Team", b =>
                {
                    b.OwnsMany("HeadendHQ.Core.Catalog.Teams.TeamLogo", "Logos", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER");

                            b1.Property<int>("ImageId")
                                .HasColumnType("INTEGER");

                            b1.Property<bool>("IsSelected")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Label")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Origin")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("TeamId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Variant")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("Id");

                            b1.HasIndex("TeamId", "Variant", "Label")
                                .IsUnique();

                            b1.ToTable("TeamLogos", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("TeamId");
                        });

                    b.Navigation("Logos");
                });

            modelBuilder.Entity("HeadendHQ.Core.Events.SportingEvent", b =>
                {
                    b.OwnsMany("HeadendHQ.Core.Events.SportingEventCastMember", "Cast", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER");

                            b1.Property<int?>("HeadshotImageId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<int>("Order")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Role")
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("SportingEventId")
                                .HasColumnType("TEXT");

                            b1.HasKey("Id");

                            b1.HasIndex("SportingEventId", "Order");

                            b1.ToTable("SportingEventCast", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("SportingEventId");
                        });

                    b.Navigation("Cast");
                });

            modelBuilder.Entity("HeadendHQ.Core.Titles.Title", b =>
                {
                    b.OwnsMany("HeadendHQ.Core.Titles.TitleCastEntry", "Cast", b1 =>
                        {
                            b1.Property<Guid>("TitleId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAddOrUpdate();

                            b1.Property<int?>("HeadshotImageId");

                            b1.Property<string>("Name")
                                .IsRequired();

                            b1.Property<string>("Role");

                            b1.HasKey("TitleId", "__synthesizedOrdinal");

                            b1.ToTable("Titles");

                            b1
                                .ToJson("Cast")
                                .HasColumnType("TEXT");

                            b1.WithOwner()
                                .HasForeignKey("TitleId");
                        });

                    b.Navigation("Cast");
                });
#pragma warning restore 612, 618
        }
    }
}
