// <auto-generated />
using HeadendHQ.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HeadendHQ.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260603140000_RefactorXmltvCache")]
    partial class RefactorXmltvCache
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("HeadendHQ.Core.HdHomerun.XmltvCache", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("XmltvContent")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("XmltvCache");
                });

            modelBuilder.Entity("HeadendHQ.Core.Titles.Title", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AdbCommand")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DummyVideoPath")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsLive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("StreamingService")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Titles");
                });

            modelBuilder.Entity("HeadendHQ.Core.Titles.Title", b =>
                {
                    b.OwnsOne("HeadendHQ.Core.Titles.TitleMetadata", "Metadata", b1 =>
                        {
                            b1.Property<Guid>("TitleId");

                            b1.Property<string>("ContentRating");

                            b1.PrimitiveCollection<string>("Genres")
                                .IsRequired();

                            b1.Property<string>("Plot");

                            b1.Property<float?>("Rating");

                            b1.PrimitiveCollection<string>("Sets")
                                .IsRequired();

                            b1.Property<string>("Studio");

                            b1.Property<string>("Tagline");

                            b1.Property<string>("UniqueId");

                            b1.Property<int?>("Year");

                            b1.HasKey("TitleId");

                            b1.ToTable("Titles");

                            b1
                                .ToJson("Metadata")
                                .HasColumnType("TEXT");

                            b1.WithOwner()
                                .HasForeignKey("TitleId");
                        });

                    b.Navigation("Metadata");
                });
#pragma warning restore 612, 618
        }
    }
}
