// <auto-generated />
using System;
using HeadendHQ.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HeadendHQ.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("HeadendHQ.Core.Assets.LeagueAsset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("League")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("LogoData")
                        .HasColumnType("BLOB");

                    b.Property<string>("Variant")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("League", "Variant")
                        .IsUnique();

                    b.ToTable("LeagueAssets", (string)null);
                });

            modelBuilder.Entity("HeadendHQ.Core.Assets.StreamingServiceAsset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("LogoData")
                        .HasColumnType("BLOB");

                    b.Property<int>("Service")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Service")
                        .IsUnique();

                    b.ToTable("StreamingServiceAssets", (string)null);
                });

            modelBuilder.Entity("HeadendHQ.Core.Assets.TeamAsset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("League")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("LogoData")
                        .HasColumnType("BLOB");

                    b.Property<string>("PrimaryColorHex")
                        .HasColumnType("TEXT");

                    b.Property<string>("SecondaryColorHex")
                        .HasColumnType("TEXT");

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TeamName", "League")
                        .IsUnique();

                    b.ToTable("TeamAssets", (string)null);
                });

            modelBuilder.Entity("HeadendHQ.Core.Assets.WordMark", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("League")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("LogoData")
                        .HasColumnType("BLOB");

                    b.Property<string>("Variant")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("League", "Variant")
                        .IsUnique();

                    b.ToTable("WordMarks", (string)null);
                });

            modelBuilder.Entity("HeadendHQ.Core.HdHomerun.XmltvCache", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("XmltvContent")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("XmltvCache", (string)null);
                });

            modelBuilder.Entity("HeadendHQ.Core.Settings.GlobalSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("EnabledStreamingServices")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TitleRetentionDays")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("GlobalSettings", (string)null);
                });

            modelBuilder.Entity("HeadendHQ.Core.Titles.Title", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AdbCommand")
                        .HasColumnType("TEXT");

                    b.Property<bool>("ArtworkCreated")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsLive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("StreamingService")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("VodLauncherPath")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Titles", (string)null);
                });

            modelBuilder.Entity("HeadendHQ.HdHomerun.HdHomerunSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DeviceUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("HdHomerunSettings", (string)null);
                });

            modelBuilder.Entity("HeadendHQ.ScheduleScraping.ScheduleScrapingSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ScrapeWindowDays")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ScheduleScrapingSettings", (string)null);
                });

            modelBuilder.Entity("HeadendHQ.VodLauncher.VodLauncherSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("LibraryPaths")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("VodLauncherSettings", (string)null);
                });

            modelBuilder.Entity("HeadendHQ.Core.Titles.Title", b =>
                {
                    b.OwnsOne("HeadendHQ.Core.Titles.TitleMetadata", "Metadata", b1 =>
                        {
                            b1.Property<Guid>("TitleId");

                            b1.Property<int?>("AwayTeamAssetId");

                            b1.Property<string>("ContentRating");

                            b1.PrimitiveCollection<string>("Genres")
                                .IsRequired();

                            b1.Property<int?>("HomeTeamAssetId");

                            b1.Property<int?>("LeagueAssetId");

                            b1.Property<string>("Plot");

                            b1.Property<float?>("Rating");

                            b1.PrimitiveCollection<string>("Sets")
                                .IsRequired();

                            b1.Property<int?>("StreamingServiceAssetId");

                            b1.Property<string>("Studio");

                            b1.Property<string>("Tagline");

                            b1.Property<string>("UniqueId");

                            b1.Property<int?>("WordMarkId");

                            b1.Property<int?>("Year");

                            b1.HasKey("TitleId");

                            b1.ToTable("Titles");

                            b1
                                .ToJson("Metadata")
                                .HasColumnType("TEXT");

                            b1.WithOwner()
                                .HasForeignKey("TitleId");
                        });

                    b.Navigation("Metadata");
                });
#pragma warning restore 612, 618
        }
    }
}
